
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[340] =
    {   0,
        2,   70,   68,   69,   67,   68,   69,   65,   69,16446,
       67,   68,   69,   68,   69,   68,   69,    4,   68,   69,
       24,   68,   69,   27,   68,   69,   68,   69,   34,   68,
       69,   35,   68,   69,   22,   68,   69,   20,   68,   69,
       31,   68,   69,   21,   68,   69,   30,   68,   69,   23,
       68,   69,   60,   68,   69,   60,   68,   69,   32,   68,
       69,   33,   68,   69,    5,   68,   69,   36,   68,   69,
        6,   68,   69,   25,   68,   69,   61,   68,   69,   61,
       68,   69,   61,   68,   69,   61,   68,   69,   61,   68,
       69,   61,   68,   69,   61,   68,   69,   61,   68,   69,

       61,   68,   69,   61,   68,   69,   61,   68,   69,   61,
       68,   69,   61,   68,   69,   61,   68,   69,   61,   68,
       69,   61,   68,   69,   61,   68,   69,   39,   68,   69,
       68,   69,   40,   68,   69,   28,   68,   69,   37,   68,
       69,   29,   68,   69,   38,   68,   69,   26,   68,   69,
        2,   67,   68,   69,   69,    3,   69,   66,   69, 8254,
       64,16446,16447,   65,16446,   10,   41,    4,   15,   41,
       16,   19,   60,   18,   60,   60,   60,   60,   17,    9,
       11,    7,    8,   17,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   44,

       61,   13,   61,   12,   61,   61,   61,   50,   61,   61,
       61,   61,   61,   61,   61,   43,    2,16446,16447, 8255,
       41,   59,   60,   60,   60,   60,   60,   60,   60,   49,
       61,   61,   61,   41,   41,   61,   61,   61,   61,   61,
       61,   55,   61,   61,   61,   41,   41,   61,   61,   48,
       61,   61,   42,   61,   61,   61,   14,   61,   61,   42,
       61,   61,   61,   60,   61,   61,   42,   61,   61,   61,
       61,   61,   61,   46,   61,   45,   61,   41,   61,   61,
       61,   61,   42,   59,   61,   61,   61,   59,   61,   61,
       61,    1,   61,   51,   61,   61,   42,   61,   54,   61,

       61,   61,   59,   61,   42,   61,   61,   61,   61,   61,
       47,   61,   58,   61,   61,   61,   61,   56,   61,   61,
       61,   53,   61,   61,   42,   61,   61,   61,   61,   61,
       52,   61,   42,   61,   57,   61,   42,   61,   42
    } ;

static const flex_int16_t yy_accept[317] =
    {   0,
        1,    1,    2,    2,    2,    2,    2,    2,    2,    3,
        5,    8,   11,   14,   16,   18,   21,   24,   27,   29,
       32,   35,   38,   41,   44,   47,   50,   53,   56,   59,
       62,   65,   68,   71,   74,   77,   80,   83,   86,   89,
       92,   95,   98,  101,  104,  107,  110,  113,  116,  119,
      122,  125,  128,  131,  133,  136,  139,  142,  145,  148,
      151,  155,  156,  158,  160,  161,  161,  163,  164,  166,
      167,  167,  168,  168,  169,  170,  170,  171,  171,  172,
      173,  173,  174,  175,  176,  177,  177,  177,  177,  178,
      178,  178,  178,  179,  179,  180,  181,  182,  183,  184,

      185,  186,  187,  188,  188,  188,  189,  190,  191,  192,
      193,  194,  195,  195,  195,  196,  197,  198,  199,  200,
      202,  204,  206,  207,  208,  210,  211,  212,  213,  214,
      215,  216,  217,  218,  219,  220,  221,  221,  222,  222,
      222,  223,  224,  224,  224,  225,  225,  225,  226,  227,
      227,  228,  229,  229,  230,  232,  233,  234,  234,  235,
      235,  235,  236,  236,  237,  238,  239,  240,  241,  242,
      244,  245,  246,  246,  247,  247,  247,  248,  248,  249,
      250,  252,  253,  255,  256,  257,  259,  260,  262,  263,
      264,  264,  264,  264,  264,  264,  264,  265,  265,  266,

      267,  267,  267,  269,  270,  271,  272,  273,  274,  276,
      278,  279,  279,  279,  280,  281,  282,  283,  286,  287,
      288,  290,  291,  291,  291,  292,  294,  294,  294,  294,
      294,  294,  294,  296,  297,  299,  301,  302,  303,  303,
      303,  303,  303,  303,  303,  305,  307,  308,  308,  309,
      310,  311,  313,  315,  315,  315,  316,  317,  318,  318,
      318,  320,  320,  320,  320,  320,  320,  320,  321,  322,
      324,  325,  327,  328,  328,  328,  328,  328,  328,  328,
      328,  329,  330,  331,  333,  333,  333,  333,  333,  333,
      333,  333,  335,  337,  339,  339,  339,  339,  339,  340,

      340,  340,  340,  340,  340,  340,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,    1,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,    1,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   47,   52,   53,   54,   47,
       55,   56,   57,   58,   59,    1,   60,   61,   62,   63,

       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   75,   47,   76,   77,   78,   79,   47,   80,   81,
       82,   47,   83,   84,   85,   86,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[87] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    1,    1,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[333] =
    {   0,
        0,  767,  769,  768,  767,  766,   84,   85,  768,  774,
      774,   88,  764,  738,   87,    0,  737,  736,   80,  774,
      774,   81,  735,  774,   70,   81,   86,  125,   94,  774,
      774,   83,  734,   79,  774,   77,  119,   88,   87,   81,
      160,   90,    0,  138,   98,   97,   80,  192,  105,  121,
      112,  142,  774,  173,  774,  733,  774,  732,  774,  774,
      753,  774,  774,  774,  774,  755,  207,  185,  216,  774,
      173,  749,    0,    0,  774,   89,  711,    0,  690,  774,
      694,  219,  680,  223,  245,  251,  196,  277,  774,  284,
      295,  227,  302,  306,  668,  774,  774,  774,  774,  664,

        0,  151,  183,  215,  221,  207,  300,  148,  230,  259,
      246,  245,  288,  223,  291,  289,  291,  127,  291,    0,
      290,    0,  292,  301,    0,  184,  297,  338,  300,  298,
      313,  353,  685,  377,  355,  774,  683,  774,  345,  358,
      774,  367,  371,  375,  217,  351,  382,  387,  394,  397,
      400,    0,  619,  420,    0,  349,  356,  377,  668,    0,
      413,  662,    0,  386,  401,  399,  363,  389,  380,    0,
      401,  403,  437,  664,    0,  435,  659,    0,  399,  418,
        0,  419,    0,  404,  430,    0,  411,    0,  417,  426,
      442,  662,  665,  458,  655,  662,  464,  484,  423,  440,

      466,  463,    0,  442,  461,  447,  458,  464,    0,    0,
      774,  469,  483,  476,  459,  482,  609,  465,  471,  470,
        0,  485,  655,  650,  476,    0,  509,  653,  657,  515,
      645,  653,    0,  480,    0,    0,  495,  487,  526,  645,
      605,  523,  555,  550,    0,    0,  499,  519,  482,  511,
      503,    0,    0,  379,  366,  502,  504,  510,  349,  326,
        0,  521,  503,  520,  525,  527,  524,  537,  555,    0,
      557,    0,  555,  548,  547,  551,  554,  554,  556,  557,
      571,  565,  555,    0,  568,  576,  567,  583,  240,  581,
      232,    0,    0,    0,  205,  589,  576,  574,  774,  577,

      578,  173,  586,  150,  576,  583,  588,  598,  615,  120,
      613,  597,   81,   68,  774,  679,  684,  689,  694,  696,
      701,  115,  706,  711,  716,  721,  726,  731,  736,  741,
      746,  751
    } ;

static const flex_int16_t yy_def[333] =
    {   0,
      315,    1,  316,  316,  316,  316,    1,    1,  315,  315,
      315,  315,  315,  315,  317,  318,  315,  315,  319,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  321,  315,  315,
      317,  315,  317,  318,  315,  319,  315,  319,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      322,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      320,  320,  320,  323,  324,  320,  320,  320,  320,  320,
      320,  320,  325,  326,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  315,  315,  315,  321,  315,  315,  315,  327,  328,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      322,  151,  151,  315,  320,  320,  320,  323,  315,  323,
      324,  315,  324,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  325,  315,  325,  326,  315,  326,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      327,  315,  327,  328,  315,  328,  315,  315,  320,  320,

      329,  330,  320,  320,  320,  320,  320,  320,  320,  320,
      315,  331,  332,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  315,  315,  320,  320,  329,  315,  329,  330,
      315,  330,  320,  320,  320,  320,  320,  320,  331,  315,
      331,  332,  315,  332,  320,  320,  320,  315,  320,  320,
      320,  320,  320,  315,  315,  320,  320,  320,  315,  315,
      320,  315,  315,  315,  315,  315,  315,  320,  320,  320,
      320,  320,  320,  315,  315,  315,  315,  315,  315,  315,
      320,  320,  320,  320,  315,  315,  315,  315,  315,  315,
      315,  320,  320,  320,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,    0,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315
    } ;

static const flex_int16_t yy_nxt[861] =
    {   0,
       10,   11,   12,   11,   13,   11,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   29,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   43,
       43,   45,   43,   46,   47,   43,   43,   48,   49,   50,
       51,   52,   43,   43,   53,   54,   55,   56,   43,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   43,   43,
       45,   43,   46,   47,   43,   48,   49,   50,   51,   52,
       43,   43,   57,   58,   59,   60,   62,   62,   11,   11,
       65,   77,   66,   67,   72,   79,   68,   75,   80,   81,

      138,   82,   82,   82,   82,   83,   99,  100,   75,   95,
       96,   97,   84,   75,   93,   93,   93,   93,  152,  113,
      102,  111,  112,  114,  299,  103,  104,  125,   88,  109,
      105,  119,  110,   89,  113,   78,  123,  299,  114,   10,
       10,  124,   73,   84,   78,   85,   86,   86,   86,  102,
      111,  112,   94,  103,  129,  125,   87,   88,  109,   88,
      119,  110,   89,  106,   89,  123,  107,  113,  130,   90,
      124,  114,  108,  120,  132,  132,  299,   91,  132,  131,
      138,  121,  129,   92,  155,   87,  122,  136,   88,  137,
      115,  104,  106,   89,  107,  105,  130,  166,   90,  113,

      108,  116,  120,  114,  117,   91,  299,  118,  131,   65,
      121,   66,  134,  155,  122,   68,  145,  145,   65,  115,
       66,   67,  159,  126,   68,  166,  127,  128,   73,  299,
      116,  156,  162,  117,  177,  118,  157,  145,  145,  142,
      142,  142,  142,   82,   82,   82,   82,  154,   86,   86,
       86,  164,  126,   88,  146,  127,  128,   88,   89,  156,
      167,  299,   89,   84,  157,   85,   86,   86,   86,   84,
      160,   86,   86,   86,   86,  146,  163,  143,  178,   88,
      164,  170,   88,  171,   89,   88,   88,   89,  299,  167,
       89,   89,  147,  172,  147,  174,  299,  148,  148,  148,

      148,  168,  169,   92,  149,  149,  149,  104,   88,  144,
      170,  105,  171,   89,   88,  151,  151,  151,  151,   89,
       84,  172,   93,   93,   93,   93,   93,   93,   93,   93,
      168,  169,  179,  180,  165,  182,   88,  211,  181,  183,
      184,   89,  150,  175,  185,  113,  187,  188,  189,  114,
      186,  190,  192,  153,  132,  132,  211,  136,  132,  137,
       94,  179,  180,  165,  182,   88,  181,  183,  184,  195,
       89,  145,  145,  185,  187,  188,  189,  138,  186,   65,
      190,   66,  134,  199,  138,   68,  138,  142,  142,  142,
      142,  142,  142,  142,  142,   86,   86,   86,   86,  200,

      193,   88,  148,  148,  148,  148,   89,  197,  197,  197,
      197,  206,  199,  196,  149,  149,  149,  149,  149,  149,
      151,  151,  151,  151,  138,  143,   89,  203,  200,  208,
       88,  204,  160,  205,  207,   89,  209,  210,   84,  206,
      154,   86,   86,   86,  211,  198,  211,  214,  215,  192,
      216,  221,  150,  217,   88,   89,  203,  208,  153,   89,
      204,  220,  205,  207,  218,  209,  210,  222,  163,  195,
      225,  219,  226,  228,  231,  214,  240,  215,   92,  216,
      221,  217,  233,   88,  197,  197,  197,  197,   89,  220,
      178,  234,  175,  218,  243,  236,  222,  193,  225,  237,

      219,  226,  238,   89,  197,  197,  197,  197,  246,  235,
      245,  233,  247,  196,  249,  250,  228,  251,  232,  252,
      234,  229,  198,  236,  241,  253,  231,  256,  237,  257,
      258,  238,   89,  240,  243,  268,  246,  235,  244,  245,
      261,  247,  249,  269,  250,  251,  270,  276,  252,  271,
      262,  263,  315,  253,  264,  256,  272,  265,  257,  258,
      273,  277,  266,  268,  229,  274,  260,  267,  278,  261,
      232,  279,  269,  280,  275,  270,  276,  271,  244,  262,
      263,  241,  281,  264,  272,  282,  265,  283,  273,  284,
      277,  266,  285,  287,  274,  267,  286,  278,  288,  290,

      279,  280,  275,  289,  291,  292,  293,  315,  294,  295,
      296,  281,  297,  298,  282,  300,  283,  303,  284,  301,
      307,  285,  287,  304,  286,  306,  305,  288,  290,  308,
      309,  289,  291,  299,  292,  293,  294,  302,  295,  296,
      310,  297,  298,  311,  300,  312,  303,  313,  301,  307,
      314,  304,  259,  306,  305,  315,  255,  308,  309,  315,
      254,  138,  138,  248,  315,  302,  224,  315,  310,  223,
      213,  212,  311,  202,  312,  201,  313,  315,  314,   62,
       62,   62,   62,   62,   71,  136,   71,   71,   71,   74,
      133,   75,   74,   74,   76,   75,   76,   76,   76,  101,

      101,  135,  135,  135,  135,  135,  158,   75,  158,  158,
      158,  161,  141,  161,  161,  161,  173,   75,  173,  173,
      173,  176,  140,  176,  176,  176,  191,  191,  191,  191,
      191,  194,  194,  194,  194,  194,  227,  227,  227,  227,
      227,  230,  230,  230,  230,  230,  239,  239,  239,  239,
      239,  242,  242,  242,  242,  242,  139,   65,  133,   75,
       75,   98,   75,   75,   75,   70,   69,  315,   64,   64,
       63,   63,   61,    9,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315
    } ;

static const flex_int16_t yy_chk[861] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    7,    8,    7,    8,
       12,   19,   12,   12,   15,   22,   12,   25,   25,   26,

       76,   26,   26,   26,   26,   27,   34,   34,   22,   32,
       32,   32,   29,   27,   29,   29,   29,   29,  322,   51,
       36,   39,   40,   51,  314,   36,   37,   47,   29,   38,
       37,   42,   38,   29,  118,   19,   45,  313,  118,    7,
        8,   46,   15,   28,   76,   28,   28,   28,   28,   36,
       39,   40,   29,   36,   49,   47,   28,   29,   38,   28,
       42,   38,   29,   37,   28,   45,   37,   41,   50,   28,
       46,   41,   37,   44,   54,   54,  310,   28,   54,   52,
       71,   44,   49,   28,  102,   28,   44,   68,   28,   68,
       41,  126,   37,   28,   37,  126,   50,  108,   28,   48,

       37,   41,   44,   48,   41,   28,  304,   41,   52,   67,
       44,   67,   67,  102,   44,   67,   87,   87,   69,   41,
       69,   69,  104,   48,   69,  108,   48,   48,   71,  302,
       41,  103,  105,   41,  114,   41,  103,  145,  145,   82,
       82,   82,   82,   84,   84,   84,   84,   92,   92,   92,
       92,  106,   48,   82,   87,   48,   48,   84,   82,  103,
      109,  295,   84,   85,  103,   85,   85,   85,   85,   86,
      104,   86,   86,   86,   86,  145,  105,   82,  114,   85,
      106,  111,   82,  112,   85,   86,   84,   82,  291,  109,
       86,   84,   88,  112,   88,  113,  289,   88,   88,   88,

       88,  110,  110,   85,   90,   90,   90,  107,   85,   86,
      111,  107,  112,   85,   86,   91,   91,   91,   91,   86,
       93,  112,   93,   93,   93,   93,   94,   94,   94,   94,
      110,  110,  115,  116,  107,  119,   93,  260,  117,  121,
      123,   93,   90,  113,  124,  128,  127,  129,  130,  128,
      124,  131,  139,   91,  132,  132,  259,  135,  132,  135,
       93,  115,  116,  107,  119,   93,  117,  121,  123,  140,
       93,  146,  146,  124,  127,  129,  130,  255,  124,  134,
      131,  134,  134,  156,  158,  134,  254,  142,  142,  142,
      142,  143,  143,  143,  143,  144,  144,  144,  144,  157,

      139,  142,  147,  147,  147,  147,  142,  148,  148,  148,
      148,  167,  156,  140,  149,  149,  149,  150,  150,  150,
      151,  151,  151,  151,  161,  142,  148,  164,  157,  169,
      142,  165,  158,  166,  168,  142,  171,  172,  154,  167,
      154,  154,  154,  154,  173,  148,  176,  179,  180,  191,
      182,  189,  149,  184,  154,  148,  164,  169,  151,  154,
      165,  187,  166,  168,  185,  171,  172,  190,  161,  194,
      199,  185,  200,  201,  202,  179,  212,  180,  154,  182,
      189,  184,  204,  154,  197,  197,  197,  197,  154,  187,
      176,  205,  173,  185,  213,  206,  190,  191,  199,  207,

      185,  200,  208,  197,  198,  198,  198,  198,  215,  205,
      214,  204,  216,  194,  218,  219,  227,  220,  202,  222,
      205,  201,  197,  206,  212,  225,  230,  234,  207,  237,
      238,  208,  197,  239,  242,  249,  215,  205,  213,  214,
      247,  216,  218,  250,  219,  220,  251,  263,  222,  256,
      248,  248,  244,  225,  248,  234,  257,  248,  237,  238,
      258,  264,  248,  249,  227,  262,  243,  248,  265,  247,
      230,  266,  250,  267,  262,  251,  263,  256,  242,  248,
      248,  239,  268,  248,  257,  269,  248,  271,  258,  273,
      264,  248,  274,  276,  262,  248,  275,  265,  277,  279,

      266,  267,  262,  278,  280,  281,  282,  241,  283,  285,
      286,  268,  287,  288,  269,  290,  271,  297,  273,  296,
      303,  274,  276,  298,  275,  301,  300,  277,  279,  305,
      306,  278,  280,  300,  281,  282,  283,  296,  285,  286,
      307,  287,  288,  308,  290,  309,  297,  311,  296,  303,
      312,  298,  240,  301,  300,  232,  231,  305,  306,  229,
      228,  224,  223,  217,  196,  296,  195,  193,  307,  192,
      177,  174,  308,  162,  309,  159,  311,  153,  312,  316,
      316,  316,  316,  316,  317,  137,  317,  317,  317,  318,
      133,  100,  318,  318,  319,   95,  319,  319,  319,  320,

      320,  321,  321,  321,  321,  321,  323,   83,  323,  323,
      323,  324,   81,  324,  324,  324,  325,   79,  325,  325,
      325,  326,   77,  326,  326,  326,  327,  327,  327,  327,
      327,  328,  328,  328,  328,  328,  329,  329,  329,  329,
      329,  330,  330,  330,  330,  330,  331,  331,  331,  331,
      331,  332,  332,  332,  332,  332,   72,   66,   61,   58,
       56,   33,   23,   18,   17,   14,   13,    9,    6,    5,
        4,    3,    2,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[70] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 1, 1, 1, 1, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 5 "lexer.l"
    #include <bits/stdc++.h>
    using namespace std;
    #include "parser.tab.h"

    stack<int> indent_stack;
    int newline_return=0;
    int dedent_count = 0;
    int line_joining_counter = 0;
    extern char* addlabel(string c);
    extern void print_ast();
    
#line 836 "lex.yy.c"

#line 838 "lex.yy.c"

#define INITIAL 0
#define INDENT_STATE 1
#define DEDENT_STATE 2
#define IMPLICIT_LINE_JOINING 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 142 "lexer.l"


#line 1070 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 316 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 774 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 144 "lexer.l"
{return ASYNC;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 145 "lexer.l"
{
            int indent = 0;
            for (int i = 0; i < strlen(yytext); i++) {
                if (yytext[i] == ' ') {
                    indent++;
                }
            }
            if(indent%2==1){
                fprintf(stderr, "IndentationError: unindent does not match any outer indentation level\n");
                print_ast();
                exit(1);
            }
            else{
                indent = indent/2;
                if (indent > indent_stack.top()) {
                    indent_stack.push(indent);
                    return INDENT;
                } else if (indent < indent_stack.top()) {
                    while (indent < indent_stack.top()) {
                        indent_stack.pop();
                        if (indent_stack.empty()) {
                            fprintf(stderr, "IndentationError: unexpected indent\n");
                            print_ast();
                            exit(1);
                        }
                        dedent_count++;
                    }
                    if (indent != indent_stack.top()) {
                        fprintf(stderr, "IndentationError: unindent does not match any outer indentation level\n");
                        print_ast();
                        exit(1);
                    }
                    unput('\n');
                    BEGIN(INDENT_STATE);
                }
            }
        }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 183 "lexer.l"
{ 
                    if(dedent_count>0){
                        dedent_count--;
                        unput('\n');
                        return DEDENT;
                    }
                    else{
                        BEGIN(INITIAL);
                    }
                }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 194 "lexer.l"
{/* ignore */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 195 "lexer.l"
{return LESS_THAN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 196 "lexer.l"
{return GREATER_THAN; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 197 "lexer.l"
{return EQUAL_EQUAL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 198 "lexer.l"
{return GREATER_THAN_EQUAL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 199 "lexer.l"
{return LESS_THAN_EQUAL; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 200 "lexer.l"
{return NOT_EQUAL; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 201 "lexer.l"
{return NOT_EQUAL_ARROW; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 202 "lexer.l"
{return IS; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 203 "lexer.l"
{ return IN;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 204 "lexer.l"
{ return NOT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 205 "lexer.l"
{ yylval.val=strdup(yytext);return ASSIGN_OPERATOR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 206 "lexer.l"
{return POWER_OPERATOR; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 207 "lexer.l"
{ yylval.val=strdup(yytext);return SHIFT_OPER; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 208 "lexer.l"
{ return FLOOR_DIV_OPER; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 209 "lexer.l"
{ return ARROW_OPER;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 210 "lexer.l"
{ return PLUS;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 211 "lexer.l"
{return MINUS;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 212 "lexer.l"
{return MULTIPLY;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 213 "lexer.l"
{return DIVIDE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 214 "lexer.l"
{return REMAINDER;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 215 "lexer.l"
{return ATTHERATE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 216 "lexer.l"
{return NEGATION;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 217 "lexer.l"
{return BIT_AND;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 218 "lexer.l"
{return BIT_XOR;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 219 "lexer.l"
{return BIT_OR;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 220 "lexer.l"
{return DOT;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 221 "lexer.l"
{return COMMA;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 222 "lexer.l"
{return COLON;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 223 "lexer.l"
{return SEMI_COLON;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 224 "lexer.l"
{line_joining_counter++; BEGIN(IMPLICIT_LINE_JOINING);return OPEN_BRACKET;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 225 "lexer.l"
{line_joining_counter--; if(line_joining_counter==0)BEGIN(INITIAL); return CLOSE_BRACKET;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 226 "lexer.l"
{return EQUAL;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 227 "lexer.l"
{line_joining_counter++; BEGIN(IMPLICIT_LINE_JOINING); return CURLY_OPEN;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 228 "lexer.l"
{line_joining_counter--; if(line_joining_counter==0)BEGIN(INITIAL);return CURLY_CLOSE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 229 "lexer.l"
{line_joining_counter++; BEGIN(IMPLICIT_LINE_JOINING);return SQUARE_OPEN;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 230 "lexer.l"
{line_joining_counter--; if(line_joining_counter==0)BEGIN(INITIAL);return SQUARE_CLOSE;}
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 231 "lexer.l"
{yylval.val=strdup(yytext); return STRING;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 232 "lexer.l"
{ yylval.val=strdup(yytext); return TYPE_HINT; }
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 233 "lexer.l"
{ /* ignore */ } 
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 235 "lexer.l"
{ return IF;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 236 "lexer.l"
{ return ELSE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 237 "lexer.l"
{ return ELIF;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 238 "lexer.l"
{ return WHILE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 239 "lexer.l"
{ return FOR;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 240 "lexer.l"
{ return AND;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 241 "lexer.l"
{ return OR;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 242 "lexer.l"
{ return BREAK;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 243 "lexer.l"
{ return CONTINUE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 244 "lexer.l"
{ return RETURN;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 245 "lexer.l"
{ return CLASS;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 246 "lexer.l"
{ return DEF;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 247 "lexer.l"
{ return GLOBAL;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 248 "lexer.l"
{ return NONLOCAL;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 249 "lexer.l"
{ return ASSERT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 250 "lexer.l"
{yylval.val=strdup(yytext); return ATOM_KEYWORDS;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 251 "lexer.l"
{ yylval.val=strdup(yytext); return NUMBER;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 252 "lexer.l"
{yylval.val=strdup(yytext); return NAME;}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 253 "lexer.l"
{}
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 254 "lexer.l"
{ }
	YY_BREAK
case 64:
/* rule 64 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 255 "lexer.l"
{return NEWLINE;}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 256 "lexer.l"
{   
                if(indent_stack.top()==0){
                    return NEWLINE;
                }
                else{
                    while (indent_stack.top()>0) {
                        newline_return=1;
                        indent_stack.pop();
                        if (indent_stack.empty()) {
                            fprintf(stderr, "IndentationError: unexpected indent\n");
                            print_ast();
                            exit(1);
                        }
                        dedent_count++;
                    }
                    unput('\n');
                    BEGIN(DEDENT_STATE);
                }
            }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 276 "lexer.l"
{ 
                    if(newline_return==1){
                        newline_return=0;
                        unput('\n');
                        return NEWLINE;
                    }
                    else if(dedent_count>0){
                        dedent_count--;
                        unput('\n');
                        return DEDENT;
                    }
                    else{
                        BEGIN(INITIAL);
                    }
                }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 292 "lexer.l"
{}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 294 "lexer.l"
{ 
                                    fprintf(stderr, "Invalid character %s at line number: %d\n", yytext, yylineno);
                                    print_ast(); 
                                    exit(1); 
                                }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 301 "lexer.l"
ECHO;
	YY_BREAK
#line 1599 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(INDENT_STATE):
			case YY_STATE_EOF(DEDENT_STATE):
			case YY_STATE_EOF(IMPLICIT_LINE_JOINING):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 316 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 316 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 315);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 301 "lexer.l"


