
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 73
#define YY_END_OF_BUFFER 74
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[339] =
    {   0,
        1,   74,   72,   73,   71,   72,   73,   69,   73,16450,
       71,   72,   73,   72,   73,   72,   73,    3,   72,   73,
       23,   72,   73,   26,   72,   73,   72,   73,   33,   72,
       73,   34,   72,   73,   21,   72,   73,   19,   72,   73,
       30,   72,   73,   20,   72,   73,   29,   72,   73,   22,
       72,   73,   63,   72,   73,   63,   72,   73,   31,   72,
       73,   32,   72,   73,    4,   72,   73,   35,   72,   73,
        5,   72,   73,   24,   72,   73,   65,   72,   73,   65,
       72,   73,   65,   72,   73,   65,   72,   73,   65,   72,
       73,   65,   72,   73,   65,   72,   73,   65,   72,   73,

       65,   72,   73,   65,   72,   73,   65,   72,   73,   65,
       72,   73,   65,   72,   73,   65,   72,   73,   65,   72,
       73,   65,   72,   73,   65,   72,   73,   65,   72,   73,
       38,   72,   73,   72,   73,   39,   72,   73,   27,   72,
       73,   65,   72,   73,   36,   72,   73,   28,   72,   73,
       37,   72,   73,   25,   72,   73,    1,   71,   72,   73,
       73,    2,   73,   70,   73, 8258,   68,16450,16451,   69,
    16450,    9,   40,    3,   14,   40,   15,   18,   63,   17,
       63,   63,   63,   63,   16,    8,   10,    6,    7,   16,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,

       65,   65,   65,   43,   65,   12,   65,   11,   65,   65,
       65,   65,   49,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   42,   65,    1,16450,16451, 8259,   40,
       56,   63,   63,   63,   63,   63,   63,   63,   48,   65,
       40,   40,   65,   65,   65,   65,   54,   65,   65,   65,
       40,   40,   65,   65,   47,   65,   65,   41,   65,   58,
       65,   65,   65,   13,   65,   65,   65,   65,   65,   41,
       65,   65,   65,   65,   65,   63,   41,   65,   65,   65,
       65,   45,   65,   44,   65,   40,   65,   65,   65,   65,
       57,   65,   65,   65,   65,   62,   65,   56,   65,   65,

       65,   65,   50,   65,   53,   65,   65,   56,   65,   41,
       65,   65,   59,   65,   64,   65,   65,   46,   65,   65,
       65,   65,   55,   65,   52,   65,   65,   65,   65,   65,
       65,   51,   65,   61,   65,   60,   65,   41
    } ;

static const flex_int16_t yy_accept[290] =
    {   0,
        1,    1,    2,    2,    2,    2,    2,    2,    2,    3,
        5,    8,   11,   14,   16,   18,   21,   24,   27,   29,
       32,   35,   38,   41,   44,   47,   50,   53,   56,   59,
       62,   65,   68,   71,   74,   77,   80,   83,   86,   89,
       92,   95,   98,  101,  104,  107,  110,  113,  116,  119,
      122,  125,  128,  131,  134,  136,  139,  142,  145,  148,
      151,  154,  157,  161,  162,  164,  166,  167,  167,  169,
      170,  172,  173,  173,  174,  174,  175,  176,  176,  177,
      177,  178,  179,  179,  180,  181,  182,  183,  183,  183,
      183,  184,  184,  184,  184,  185,  185,  186,  187,  188,

      189,  190,  191,  192,  193,  193,  193,  194,  195,  196,
      197,  198,  199,  199,  199,  200,  201,  202,  203,  204,
      206,  208,  210,  211,  212,  213,  215,  216,  217,  218,
      219,  220,  221,  222,  223,  224,  225,  226,  227,  228,
      229,  230,  230,  231,  231,  231,  232,  233,  233,  233,
      234,  234,  234,  235,  236,  236,  237,  238,  238,  239,
      241,  241,  242,  242,  242,  243,  243,  244,  245,  246,
      247,  249,  250,  251,  251,  252,  252,  252,  253,  253,
      254,  255,  257,  258,  260,  262,  263,  264,  266,  267,
      268,  269,  270,  272,  273,  274,  275,  276,  276,  276,

      276,  276,  276,  276,  277,  277,  277,  277,  279,  280,
      281,  282,  284,  286,  287,  287,  287,  288,  289,  290,
      291,  293,  294,  295,  296,  298,  300,  301,  302,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  305,  307,
      308,  308,  308,  308,  308,  308,  308,  310,  312,  313,
      313,  315,  317,  318,  320,  321,  322,  322,  322,  323,
      323,  323,  325,  325,  325,  325,  325,  327,  328,  329,
      330,  330,  330,  330,  330,  331,  332,  334,  334,  334,
      334,  334,  336,  338,  338,  338,  339,  339,  339
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,    1,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,    1,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   49,   50,   51,   47,   52,   53,   47,   47,
       54,   55,   56,   57,   58,    1,   59,   60,   61,   62,

       63,   64,   65,   66,   67,   68,   69,   70,   71,   72,
       73,   74,   47,   75,   76,   77,   78,   47,   79,   80,
       47,   47,   81,   82,   83,   84,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[85] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    1,    1,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    1,    1,    1,    1,    4,    4,    4,
        4,    4,    4,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[306] =
    {   0,
        0,  697,  699,  698,  697,  696,   82,   83,  698,  704,
      704,   86,  694,  668,   85,    0,  667,  666,   78,  704,
      704,   79,  665,  704,   68,   79,   84,  122,   92,  704,
      704,   81,  664,   77,  704,   75,  113,   78,   89,   86,
      156,   89,    0,  127,  114,   97,   51,   91,  161,  159,
      130,  110,  134,  704,  204,  704,  663,  632,  704,  661,
      704,  704,  682,  704,  704,  704,  704,  684,  208,  131,
      229,  704,  157,  678,    0,    0,  704,  172,  640,    0,
      619,  704,  623,  218,  609,  222,  242,  248,  197,  271,
      704,  226,  275,  280,  296,  300,  597,  704,  704,  704,

      704,  593,    0,  189,  175,  204,  183,  300,  219,  208,
      243,  289,  305,  279,  267,  269,  185,  317,  282,    0,
      276,    0,  286,  290,  296,    0,  302,  299,  336,  295,
      339,  307,  304,  306,  311,  379,  318,  614,  388,  270,
      704,  612,  704,  359,  320,  704,  377,  381,  385,  365,
      108,  397,  403,  407,  410,  415,    0,  549,  427,    0,
      387,  598,    0,  358,  593,    0,  341,  357,  392,  397,
        0,  408,  417,  402,  596,    0,  403,  590,    0,  405,
      424,    0,  424,    0,    0,  409,  425,    0,  419,  427,
      415,  433,    0,  435,  433,  445,  446,  445,  588,  592,

      466,  581,  589,  485,  489,  471,  475,    0,  448,  447,
      455,    0,    0,  704,  474,  487,  481,  451,  487,  537,
        0,  464,  484,  476,    0,    0,  485,  488,  488,  580,
      575,  494,  578,  580,  503,  564,  536,    0,    0,  488,
      525,  426,  419,  522,  384,  389,    0,    0,  493,  518,
        0,    0,  492,    0,  493,  503,  372,  364,  494,  366,
      262,    0,  495,  514,  517,  502,    0,  210,  196,  527,
      524,  525,  523,  526,  179,  150,    0,  529,  544,  133,
      123,    0,    0,  118,  531,  704,   79,  704,  608,  613,
      618,  623,  625,  630,  113,  635,  640,  645,  650,  655,

      660,  665,  670,  675,  680
    } ;

static const flex_int16_t yy_def[306] =
    {   0,
      288,    1,  289,  289,  289,  289,    1,    1,  288,  288,
      288,  288,  288,  288,  290,  291,  288,  288,  292,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  288,  288,  288,  288,  293,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  294,
      288,  288,  290,  288,  290,  291,  288,  292,  288,  292,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  295,  288,  288,  288,  288,  288,  288,  288,

      288,  288,  293,  293,  296,  297,  293,  293,  293,  293,
      293,  293,  298,  299,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  288,  293,  288,  288,  294,
      288,  288,  288,  300,  301,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  295,  156,  156,  288,  293,
      296,  288,  296,  297,  288,  297,  293,  293,  293,  293,
      293,  293,  293,  298,  288,  298,  299,  288,  299,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  300,  288,  300,

      301,  288,  301,  288,  288,  302,  303,  293,  293,  293,
      293,  293,  293,  288,  304,  305,  293,  293,  293,  293,
      293,  293,  293,  293,  293,  293,  293,  293,  293,  288,
      288,  302,  288,  302,  303,  288,  303,  293,  293,  293,
      304,  288,  304,  305,  288,  305,  293,  293,  293,  288,
      293,  293,  293,  293,  293,  293,  288,  288,  293,  288,
      288,  293,  288,  288,  288,  288,  293,  293,  293,  293,
      288,  288,  288,  288,  293,  293,  293,  288,  288,  288,
      288,  293,  293,  288,  288,  288,  288,    0,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,

      288,  288,  288,  288,  288
    } ;

static const flex_int16_t yy_nxt[789] =
    {   0,
       10,   11,   12,   11,   13,   11,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   29,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   44,   43,
       43,   45,   43,   46,   47,   48,   43,   49,   50,   51,
       52,   53,   43,   54,   55,   56,   57,   58,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   43,   43,   45,
       43,   46,   47,   48,   49,   50,   51,   52,   53,   43,
       59,   60,   61,   62,   64,   64,   11,   11,   67,   79,
       68,   69,   74,   81,   70,   77,   82,   83,  126,   84,

       84,   84,   84,   85,  101,  102,   77,   97,   98,   99,
       86,   77,   95,   95,   95,   95,  157,  113,  104,  109,
      105,  114,  110,  111,  106,  126,   90,  112,  150,  150,
      119,   91,   80,  141,  286,  142,   10,   10,  127,   75,
       86,  125,   87,   88,   88,   88,  104,  109,  123,   96,
      110,  111,  124,   89,   90,  112,   90,  107,  119,   91,
      108,   91,  120,  113,  143,  127,   92,  114,  113,  125,
      121,  135,  114,  286,   93,  122,  123,  134,  286,   94,
      124,   89,  162,  143,   90,  107,  115,  108,  286,   91,
      120,  128,  129,  132,   92,  130,  131,  116,  121,  135,

      117,   93,  122,  118,  134,  136,  136,  283,  133,  136,
       67,   75,   68,  139,  115,  165,   70,  150,  150,  128,
      129,  132,  160,  130,  131,  116,   80,  167,  117,  163,
      118,   67,  182,   68,   69,  133,  282,   70,  147,  147,
      147,  147,   84,   84,   84,   84,  154,  154,  154,  169,
      160,  170,   90,  276,  151,  167,   90,   91,  166,  182,
       86,   91,   87,   88,   88,   88,   86,  275,   88,   88,
       88,   88,  141,  214,  142,  148,   90,  169,  171,  170,
       90,   91,   90,  155,   90,   91,  152,   91,  152,   91,
      178,  153,  153,  153,  153,  156,  156,  156,  156,   94,

      159,   88,   88,   88,   90,  149,  171,  105,  180,   91,
       90,  106,  175,  181,   86,   91,   95,   95,   95,   95,
       95,   95,   95,   95,  113,  184,  183,  172,  114,  185,
       90,  202,  158,  179,  168,   91,  180,  173,  186,  187,
      189,  181,  190,  105,  191,  188,  113,  106,  192,  195,
      114,  193,  184,   96,  183,  172,  194,  185,   90,  176,
      196,  197,  168,   91,  173,  186,  199,  187,  189,  143,
      190,  191,  188,  214,  203,  143,  192,  195,  193,  143,
      136,  136,  208,  194,  136,  150,  150,  209,  196,  197,
       67,  288,   68,  139,  143,  261,   70,  147,  147,  147,

      147,  147,  147,  147,  147,   88,   88,   88,   88,  214,
      208,   90,  166,  200,  214,  209,   91,  153,  153,  153,
      153,  288,  151,  204,  204,  204,  204,  154,  154,  154,
      154,  154,  154,  260,  148,  156,  156,  156,  156,   90,
      210,  163,   91,  212,   91,   86,  211,  159,   88,   88,
       88,  213,  199,  217,  218,  219,  176,  179,  220,  221,
      205,   90,  222,  223,  155,  224,   91,  210,  225,  226,
       91,  212,  158,  211,  227,  228,  229,  202,  233,  213,
      217,  242,  218,  219,   94,  220,  236,  221,  238,   90,
      222,  223,  224,  240,   91,  239,  225,  226,  245,  200,

      248,  233,  227,  228,  229,  204,  204,  204,  204,  204,
      204,  204,  204,  251,  236,  247,  238,  249,  252,  254,
      203,  240,  239,  253,   91,  234,  255,  248,  243,  237,
      256,  259,  242,  245,  262,  267,  268,  269,  288,  271,
      251,  246,  205,  247,  270,  249,  252,  254,  234,  263,
      253,  274,   91,  264,  255,  272,  265,  237,  256,  259,
      273,  277,  262,  267,  268,  269,  266,  271,  278,  279,
      284,  270,  280,  281,  285,  258,  246,  263,  274,  243,
      287,  264,  288,  272,  265,  257,  143,  143,  273,  277,
      250,  288,  231,  266,  288,  230,  278,  279,  284,  280,

      281,  216,  285,  215,  207,  206,  288,  287,   64,   64,
       64,   64,   64,   73,  141,   73,   73,   73,   76,  138,
       77,   76,   76,   78,   77,   78,   78,   78,  103,  103,
      140,  140,  140,  140,  140,  161,   77,  161,  161,  161,
      164,  146,  164,  164,  164,  174,   77,  174,  174,  174,
      177,  145,  177,  177,  177,  198,  198,  198,  198,  198,
      201,  201,  201,  201,  201,  232,  232,  232,  232,  232,
      235,  235,  235,  235,  235,  241,  241,  241,  241,  241,
      244,  244,  244,  244,  244,  144,   67,  138,   77,  137,
       77,  100,   77,   77,   77,   72,   71,  288,   66,   66,

       65,   65,   63,    9,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288
    } ;

static const flex_int16_t yy_chk[789] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,    8,    7,    8,   12,   19,
       12,   12,   15,   22,   12,   25,   25,   26,   47,   26,

       26,   26,   26,   27,   34,   34,   22,   32,   32,   32,
       29,   27,   29,   29,   29,   29,  295,   52,   36,   38,
       37,   52,   38,   39,   37,   47,   29,   40,  151,  151,
       42,   29,   19,   70,  287,   70,    7,    8,   48,   15,
       28,   46,   28,   28,   28,   28,   36,   38,   45,   29,
       38,   39,   45,   28,   29,   40,   28,   37,   42,   29,
       37,   28,   44,   41,   73,   48,   28,   41,   49,   46,
       44,   53,   49,  284,   28,   44,   45,   51,  281,   28,
       45,   28,  105,   78,   28,   37,   41,   37,  280,   28,
       44,   49,   49,   50,   28,   49,   49,   41,   44,   53,

       41,   28,   44,   41,   51,   55,   55,  276,   50,   55,
       69,   73,   69,   69,   41,  106,   69,   89,   89,   49,
       49,   50,  104,   49,   49,   41,   78,  107,   41,  105,
       41,   71,  117,   71,   71,   50,  275,   71,   84,   84,
       84,   84,   86,   86,   86,   86,   92,   92,   92,  109,
      104,  110,   84,  269,   89,  107,   86,   84,  106,  117,
       87,   86,   87,   87,   87,   87,   88,  268,   88,   88,
       88,   88,  140,  261,  140,   84,   87,  109,  111,  110,
       84,   87,   88,   92,   86,   84,   90,   88,   90,   86,
      114,   90,   90,   90,   90,   93,   93,   93,   93,   87,

       94,   94,   94,   94,   87,   88,  111,  108,  115,   87,
       88,  108,  113,  116,   95,   88,   95,   95,   95,   95,
       96,   96,   96,   96,  118,  121,  119,  112,  118,  123,
       95,  145,   93,  114,  108,   95,  115,  112,  124,  125,
      127,  116,  128,  129,  130,  125,  131,  129,  132,  135,
      131,  133,  121,   95,  119,  112,  134,  123,   95,  113,
      137,  137,  108,   95,  112,  124,  144,  125,  127,  164,
      128,  130,  125,  260,  145,  258,  132,  135,  133,  257,
      136,  136,  167,  134,  136,  150,  150,  168,  137,  137,
      139,  246,  139,  139,  161,  245,  139,  147,  147,  147,

      147,  148,  148,  148,  148,  149,  149,  149,  149,  174,
      167,  147,  164,  144,  177,  168,  147,  152,  152,  152,
      152,  243,  150,  153,  153,  153,  153,  154,  154,  154,
      155,  155,  155,  242,  147,  156,  156,  156,  156,  147,
      169,  161,  153,  172,  147,  159,  170,  159,  159,  159,
      159,  173,  198,  180,  181,  183,  174,  177,  186,  187,
      153,  159,  189,  190,  154,  191,  159,  169,  192,  194,
      153,  172,  156,  170,  195,  196,  197,  201,  206,  173,
      180,  215,  181,  183,  159,  186,  207,  187,  209,  159,
      189,  190,  191,  211,  159,  210,  192,  194,  216,  198,

      218,  232,  195,  196,  197,  204,  204,  204,  204,  205,
      205,  205,  205,  222,  235,  217,  209,  219,  223,  227,
      201,  211,  210,  224,  204,  206,  228,  218,  215,  207,
      229,  240,  241,  244,  249,  253,  255,  256,  237,  263,
      222,  216,  204,  217,  259,  219,  223,  227,  232,  250,
      224,  266,  204,  250,  228,  264,  250,  235,  229,  240,
      265,  270,  249,  253,  255,  256,  250,  263,  271,  272,
      278,  259,  273,  274,  279,  236,  244,  250,  266,  241,
      285,  250,  234,  264,  250,  233,  231,  230,  265,  270,
      220,  203,  202,  250,  200,  199,  271,  272,  278,  273,

      274,  178,  279,  175,  165,  162,  158,  285,  289,  289,
      289,  289,  289,  290,  142,  290,  290,  290,  291,  138,
      102,  291,  291,  292,   97,  292,  292,  292,  293,  293,
      294,  294,  294,  294,  294,  296,   85,  296,  296,  296,
      297,   83,  297,  297,  297,  298,   81,  298,  298,  298,
      299,   79,  299,  299,  299,  300,  300,  300,  300,  300,
      301,  301,  301,  301,  301,  302,  302,  302,  302,  302,
      303,  303,  303,  303,  303,  304,  304,  304,  304,  304,
      305,  305,  305,  305,  305,   74,   68,   63,   60,   58,
       57,   33,   23,   18,   17,   14,   13,    9,    6,    5,

        4,    3,    2,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288,  288,  288,
      288,  288,  288,  288,  288,  288,  288,  288
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[74] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,     };

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 5 "lexer.l"
    #include <bits/stdc++.h>
    // #include "data.h"
    // #include "data.cpp"
    // #include "symbol_table.h"
    #include "data.cpp"
    using namespace std;
    #include "parser.tab.h"

    stack<int> indent_stack;
    int newline_return=0;
    int dedent_count = 0;
    int line_joining_counter = 0;

    void noding(char* yytext,string type=""){
        yylval.elem = create_node(1, strdup(yytext));
        yylval.elem->lineno = yylineno;
        if(type=="NUMBER"){
            for(int i=0;i<strlen(yytext);i++){
                if(yytext[i]=='.'){
                    yylval.elem->type = strdup("float");
                    yylval.elem->atom_type = strdup("float");
                    return;     
                }
            }
            yylval.elem->type = strdup("int");
            yylval.elem->atom_type = "int";
        }
    }
    
#line 828 "lex.yy.c"

#line 830 "lex.yy.c"

#define INITIAL 0
#define INDENT_STATE 1
#define DEDENT_STATE 2
#define IMPLICIT_LINE_JOINING 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 163 "lexer.l"


#line 1062 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 289 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 704 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 165 "lexer.l"
{
            int indent = 0;
            for (int i = 0; i < strlen(yytext); i++) {
                if (yytext[i] == ' ') {
                    indent++;
                }
            }
            if(indent%2==1){
                fprintf(stderr, "IndentationError: unindent does not match any outer indentation level\n");
                // print_ast();
                exit(1);
            }
            else{
                indent = indent/2;
                if (indent > indent_stack.top()) {
                    indent_stack.push(indent);
                    noding(yytext); return INDENT;
                } else if (indent < indent_stack.top()) {
                    while (indent < indent_stack.top()) {
                        indent_stack.pop();
                        if (indent_stack.empty()) {
                            fprintf(stderr, "IndentationError: unexpected indent\n");
                            // print_ast();
                            exit(1);
                        }
                        dedent_count++;
                    }
                    if (indent != indent_stack.top()) {
                        fprintf(stderr, "IndentationError: unindent does not match any outer indentation level\n");
                        // print_ast();
                        exit(1);
                    }
                    unput('\n');
                    BEGIN(INDENT_STATE);
                }
            }
        }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 203 "lexer.l"
{ 
                    if(dedent_count>0){
                        dedent_count--;
                        unput('\n');
                        noding(yytext); return DEDENT;
                    }
                    else{
                        BEGIN(INITIAL);
                    }
                }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 214 "lexer.l"
{/* ignore */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 215 "lexer.l"
{noding(yytext);return LESS_THAN; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 216 "lexer.l"
{noding(yytext); return GREATER_THAN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 217 "lexer.l"
{noding(yytext); return EQUAL_EQUAL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 218 "lexer.l"
{noding(yytext); return GREATER_THAN_EQUAL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 219 "lexer.l"
{noding(yytext); return LESS_THAN_EQUAL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 220 "lexer.l"
{noding(yytext); return NOT_EQUAL; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 221 "lexer.l"
{noding(yytext); return NOT_EQUAL_ARROW; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 222 "lexer.l"
{noding(yytext); return IS; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 223 "lexer.l"
{ noding(yytext); return IN;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 224 "lexer.l"
{ noding(yytext); return NOT;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 225 "lexer.l"
{ noding(yytext); return ASSIGN_OPERATOR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 226 "lexer.l"
{noding(yytext); return POWER_OPERATOR; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 227 "lexer.l"
{ noding(yytext); return SHIFT_OPER; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 228 "lexer.l"
{ noding(yytext); return FLOOR_DIV_OPER; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 229 "lexer.l"
{ noding(yytext); return ARROW_OPER;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 230 "lexer.l"
{ noding(yytext); return PLUS;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 231 "lexer.l"
{noding(yytext); return MINUS;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 232 "lexer.l"
{noding(yytext); return MULTIPLY;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 233 "lexer.l"
{noding(yytext); return DIVIDE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 234 "lexer.l"
{noding(yytext); return REMAINDER;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 235 "lexer.l"
{noding(yytext); return ATTHERATE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 236 "lexer.l"
{noding(yytext); return NEGATION;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 237 "lexer.l"
{noding(yytext); return BIT_AND;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 238 "lexer.l"
{noding(yytext); return BIT_XOR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 239 "lexer.l"
{noding(yytext); return BIT_OR;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 240 "lexer.l"
{noding(yytext); return DOT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 241 "lexer.l"
{noding(yytext); return COMMA;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 242 "lexer.l"
{noding(yytext); return COLON;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 243 "lexer.l"
{noding(yytext); return SEMI_COLON;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 244 "lexer.l"
{line_joining_counter++; BEGIN(IMPLICIT_LINE_JOINING); noding(yytext); return OPEN_BRACKET;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 245 "lexer.l"
{line_joining_counter--; if(line_joining_counter==0)BEGIN(INITIAL); noding(yytext); return CLOSE_BRACKET;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 246 "lexer.l"
{noding(yytext); return EQUAL;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 247 "lexer.l"
{line_joining_counter++; BEGIN(IMPLICIT_LINE_JOINING); noding(yytext); return CURLY_OPEN;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 248 "lexer.l"
{line_joining_counter--; if(line_joining_counter==0)BEGIN(INITIAL); noding(yytext); return CURLY_CLOSE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 249 "lexer.l"
{line_joining_counter++; BEGIN(IMPLICIT_LINE_JOINING); noding(yytext); return SQUARE_OPEN;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 250 "lexer.l"
{line_joining_counter--; if(line_joining_counter==0)BEGIN(INITIAL); noding(yytext); return SQUARE_CLOSE;}
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 251 "lexer.l"
{noding(yytext);  return STRING;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 252 "lexer.l"
{noding(yytext); return TYPE_HINT; }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 253 "lexer.l"
{ /* ignore */ } 
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 255 "lexer.l"
{ noding(yytext); return IF;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 256 "lexer.l"
{noding(yytext);  return ELSE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 257 "lexer.l"
{noding(yytext);  return ELIF;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 258 "lexer.l"
{ noding(yytext); return WHILE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 259 "lexer.l"
{noding(yytext);  return FOR;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 260 "lexer.l"
{noding(yytext);  return AND;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 261 "lexer.l"
{noding(yytext);  return OR;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 262 "lexer.l"
{ noding(yytext); return BREAK;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 263 "lexer.l"
{noding(yytext);  return CONTINUE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 264 "lexer.l"
{noding(yytext);  return RETURN;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 265 "lexer.l"
{noding(yytext);  return CLASS;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 266 "lexer.l"
{noding(yytext);  return DEF;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 267 "lexer.l"
{ noding(yytext); return GLOBAL;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 268 "lexer.l"
{noding(yytext);  return ATOM_KEYWORDS;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 269 "lexer.l"
{noding(yytext);  return NONE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 270 "lexer.l"
{noding(yytext);  return LEN;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 271 "lexer.l"
{noding(yytext);  return PRINT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 272 "lexer.l"
{noding(yytext);  return D_NAME;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 273 "lexer.l"
{noding(yytext);  return D_MAIN;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 274 "lexer.l"
{noding(yytext);  return SELF;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 275 "lexer.l"
{ noding(yytext,"NUMBER");  return NUMBER;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 276 "lexer.l"
{ noding(yytext); return RANGE;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 277 "lexer.l"
{ noding(yytext); return NAME;}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 278 "lexer.l"
{}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 279 "lexer.l"
{ }
	YY_BREAK
case 68:
/* rule 68 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 280 "lexer.l"
{noding(yytext); return NEWLINE;}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 281 "lexer.l"
{   
                if(indent_stack.top()==0){
                    noding(yytext); return NEWLINE;
                }
                else{
                    while (indent_stack.top()>0) {
                        newline_return=1;
                        indent_stack.pop();
                        if (indent_stack.empty()) {
                            fprintf(stderr, "IndentationError: unexpected indent\n");
                            // print_ast();
                            exit(1);
                        }
                        dedent_count++;
                    }
                    unput('\n');
                    BEGIN(DEDENT_STATE);
                }
            }
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 301 "lexer.l"
{ 
                    if(newline_return==1){
                        newline_return=0;
                        unput('\n');
                        noding(yytext); return NEWLINE;
                    }
                    else if(dedent_count>0){
                        dedent_count--;
                        unput('\n');
                        noding(yytext); 
                        return DEDENT;
                    }
                    else{
                        BEGIN(INITIAL);
                    }
                }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 318 "lexer.l"
{}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 320 "lexer.l"
{ 
                                    fprintf(stderr, "Invalid character %s at line number: %d\n", yytext, yylineno);
                                    // print_ast(); 
                                    exit(1); 
                                }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 327 "lexer.l"
ECHO;
	YY_BREAK
#line 1612 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(INDENT_STATE):
			case YY_STATE_EOF(DEDENT_STATE):
			case YY_STATE_EOF(IMPLICIT_LINE_JOINING):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 289 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 289 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 288);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 327 "lexer.l"


